clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 10

    # The number of clients selected in each round
    per_round: 10

    # Should the clients compute test accuracy locally?
    do_test: false

    # Processors for outbound data payloads

    bandwidth:
    - 5.6
    - 15.2
    - 12.8
    - 4
    - 6.4
    - 13.6
    - 10.4
    - 8
    - 8.8
    - 11.2

    cpu_freq:
    - 1600
    - 1500
    - 1200
    - 1900
    - 1100
    - 1800
    - 1400
    - 1000
    - 1700
    - 1300

    cn:
    - 10
    - 22
    - 16
    - 18
    - 14
    - 20
    - 28
    - 24
    - 12
    - 26


    # 最大cpu频率，单位MHZ
    max_cpu_freq: 2000

    # 最小cpu频率
    min_cpu_freq: 1000

    # 单个大小
    sample_size: 5

server:
    address: 127.0.0.1
    port: 18000
    # random_seed: 1
    simulate_wall_time: true

    do_test: true

    # Processors for inbound data payloads

data:
    # The training and testing dataset
    datasource: CIFAR10

    # Where the dataset is located
    data_path: ./data

    # Number of samples in each partition
    min_partition_size: 2000

    # IID or non-IID?
    sampler: fixed_noniid

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 200

    # The maximum number of clients running concurrently
    max_concurrency: 6

    # The target accuracy
    target_accuracy: 0.95

    # The machine learning model
    model_name: resnet_18

    # Number of epoches for local training in each communication round
    epochs: 5
    batch_size: 64
    optimizer: SGD
    lr_scheduler: StepLR

algorithm:
    # The initial synchronization frequency
    type: fedavg
    solver: greedy
    global_learning_rate: 1
    lr_decay: 0.998
    alpha: 0.5
    B: 96


parameters:
    optimizer:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0

    learning_rate:
        step_size: 1
        gamma: 1